### ISSUE TITLE
Invalid links in Modulith section in spring.io 

### ISSUE THREAD

**Issue by kamchy** [spring-projects/spring-modulith#736]
Spring-modulith "landing page" (https://spring.io/projects/spring-modulith) contains invalid links in Overview "tab". The links are rendered as empty "Oops, 404" pages:

For example: 

https://docs.spring.io/spring-modulith/docs/current/reference/html/#fundamentals.modules.application-modules

https://docs.spring.io/spring-modulith/docs/current/reference/html/#observability 

I've noticed https://docs.spring.io/spring-modulith/docs/current/ contains only api subdirectory (there is no reference) whereas https://docs.spring.io/spring-modulith/docs/current-SNAPSHOT/ contains both api and reference.

I'm not sure if this is the right repository to raise this issue. Please let me know if I should raise it somewhere else.

**Comment by breun** [comment]
The link to the reference documentation for the current version (1.2.1) on https://spring.io/projects/spring-modulith#learn points to https://docs.spring.io/spring-modulith/reference/current/, which also returns 404 Not Found.

**Comment by odrotbohm** [comment]
Thanks for bringing this up! This was a mismatch between the version handling of our website and Antora. The former should point to the version explicitly, i.e. https://docs.spring.io/spring-modulith/reference/1.2.1. I've fixed that for the project page.

**Comment by kamchy** [comment]
@odrotbohm - I'm not sure wha Anthora is and I still see invalid links. Therefore I have one question: should I expect the website to contain correct links now? When I go to https://spring.io/projects/spring-modulith#overview and click links in overview "tab" I still get 404: 
![Screenshot 2024-08-05 at 09 35 26 Medium](https://github.com/user-attachments/assets/784fc7f4-a43b-4c23-af96-d63dc08eabff)

**Comment by odrotbohm** [comment]
Thanks for following up. Those links should be fixed now, too.

**Comment by kamchy** [comment]
Thank you, @odrotbohm!
